apiVersion: v1
kind: Service
metadata:
  name: service-claims
spec:
  selector:
    app: service-claims
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 30003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-claims
spec:
  selector:
    matchLabels:
      app: service-claims
  replicas: 1
  template:
    metadata:
      labels:
        app: service-claims
    spec:
      containers:
        - name: server-claims
          image: tkchmax/service-claims
          ports:
            - name: http
              containerPort: 8082